export const ERRORS = {
    UNAUTHORIZED: { message: "Para ver tus propiedades, debes autenticarte", status: 401 },
    NOT_FOUND: { message: "La propiedad no existe", status: 404 },
    FORBIDDEN: { message: "No tienes permiso para ver esta propiedad", status: 403 },
    SERVER_ERROR: { message: "Error en el servidor", status: 500 },
    NOT_EXIST_TOKEN: { message: "El token no existe", status: 404 },
    EXPIRED_TOKEN: { message: "El token ha expirado, solicite uno nuevo", status: 404 },
    EMAIL_ALREADY_REGISTERED: { message: "Este correo ya está registrado", status: 400 },
    EMAIL_OR_PHONE_ALREADY_REGISTERED: { message: "Este correo o teléfono ya estan registrados", status: 400 },
    USER_NOT_CONFIRMED: { message: "El usuario no está confirmado", status: 403 },
    MANUAL_ACCOUNT_EXISTS: { message: "El usuario ya fue registrado de forma manual", status: 400 },
    ACCOUNT_NOT_CONFIRMED: { message: "La cuenta no ha sido confirmada, hemos enviado un nuevo token a tu email para confirmar tu cuenta", status: 401 },
    INCORRECT_PASSWORD: { message: "Contraseña incorrecta", status: 401 },
    USER_NOT_FOUND: { message: "Usuario no encontrado", status: 404 },
    PHONE_EXIST: { message: "El número ingresado ya está registrado", status: 409 },
    IMAGE_UPLOAD_ERROR: { message: "Error al subir imágenes", status: 500 },
    AUTH_REQUIRED_CREATE_PROPERTY: { message: "Para crear una propiedad, debes autenticarte", status: 401 },
    AUTH_REQUIRED_DELETE_PROPERTY: { message: "Para eliminar una propiedad, debes autenticarte", status: 401 },
    AUTH_REQUIRED_EDIT_PROPERTY: { message: "Para editar una propiedad, debes autenticarte", status: 401 },
    AUTH_REQUIRED_COMPLETE_ACCOUNT: { message: "Para completar la información de tu cuenta, debes autenticarte", status: 401 },
    FORBIDDEN_DELETE_PROPERTY: { message: "No tienes permiso para eliminar esta propiedad", status: 403 },
    FORBIDDEN_EDIT_PROPERTY: { message: "No tienes permiso para editar esta propiedad", status: 403 },
    NOT_RESULTS: {message: "No se encontraron resultados en tu busqueda", status: 404},
    UNAUTHORIZED_INFO: {message: "Para solicitar tu información, debes estar autenticado", status: 401},
    DUPLICATE_UPDATE: {message: "No puedes actualizar tu información si es la misma que tienes registrada", status: 400},
    EXTERNAL_PROVIDER_UPDATE: {message: "No puedes actualizar tu información mientras estás autenticado con un proveedor externo como Google", status: 400}
};
